---
title: "Large datasets"
author: "Anonymous"
date: "2025-03-06"
output: html_document
bibliography: references.bib
  nocite: |
    @wickham2023r
---

## Initialisation

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#rm(list = ls())
library(Rcompadre)
library(tidyverse)
library(here)
library(phytools)
library(taxize)
library(Rage)
library(popbio)
library(svglite)
source(here("Functions.R"))
```

# introduction

# Compadre

## Acessing Data

```{r}
Comadre <- cdb_fetch("comadre")
ComSub <- subset(Comadre,
                   Class == "Aves" & #
                   MatrixTreatment == "Unmanipulated" &
                   MatrixCaptivity == "W") 
```

## Manipulation

```{r}
ComFlag <- cdb_flag(ComSub)
ComSubFlag <- subset(ComFlag,
                      check_NA_A == FALSE &
                      check_ergodic == TRUE)
```

## Data

### Histograms

```{r warning=FALSE, message=FALSE}
ComSubFlag$lambda <- unlist(lapply(matA(ComSubFlag), 
                                   popbio::lambda))

ComSubFlag$generation_time <- unlist(lapply(matA(ComSubFlag), 
                                   popbio::generation.time))
GVG <- as_data_frame(ComSubFlag) %>%
  select(lambda, generation_time) %>% 
  mutate(across(everything(), ~ na_if(., Inf))) %>% 
  mutate(across(everything(), ~ na_if(., -Inf))) %>%
  drop_na()

#Examine the distribution of population growth rates:
GrowthHist <- histogram(GVG, GVG$lambda,
                        "Population Growth Rate(λ)", 
                        "Histogram of Growth Rate Within the Aves Clade"
                        , 0.2, TRUE)

GenHist <- histogram(GVG, GVG$generation_time,
                        "Generation Time (years)", 
                        "Histogram of Generation Time Within the Aves Clade"
                        , 1, FALSE)



GrowthHist
GenHist
```

### relationship

```{r warning=FALSE, message=FALSE}
GenVGrowth <- scatterplot(GVG, GVG$generation_time, 
                          "Generation Time (years)", 
                          GVG$lambda,
                          "Growth Rate (λ)", 
                          "Generation time Vs Growth Rate in the Aves Clade"
                          , FALSE)

GenVGrowth
```

### Linear model

normal

```{r}
CGVG <- subset(GVG, generation_time < 50)

GVGMod <- lm(lambda ~ generation_time, GVG)
diagnostic_plots("GVGMod DP.svg", GVGMod)

CGVGMod <- lm(lambda ~ generation_time, CGVG)
diagnostic_plots("CGVGMod DP.svg", CGVGMod)
```

log transformed

```{r}
LGVGMod <- lm(log(lambda) ~ log(generation_time), GVG)
diagnostic_plots("LGVGMod DP.svg", LGVGMod)

LCGVGMod <- lm(log(lambda) ~ log(generation_time), CGVG)
diagnostic_plots("LCGVGMod DP.svg", LCGVGMod)
```

polynomial

```{r}
PGVGMod <- lm(lambda ~ generation_time + I(generation_time^2) + I(generation_time^3), GVG)
diagnostic_plots("PGVGMod DP.svg", PGVGMod)

PCGVGMod <- lm(lambda ~ generation_time + I(generation_time^2) + I(generation_time^3), CGVG)
diagnostic_plots("PCGVGMod DP.svg", PCGVGMod)
```

generalized

```{r}
GGVGMod <- glm(lambda ~ generation_time, GVG)
diagnostic_plots("GGVGMod DP.svg", GGVGMod)

GGVGMod <- glm(lambda ~ generation_time, CGVG)
diagnostic_plots("GCGVGMod DP.svg", GCGVGMod)
```

### Plotting

```{r}
GenVGrowth2 <- scatterplot(GVG, log(GVG$generation_time), 
                          "Log transformed Generation Time (years)", 
                          log(GVG$lambda),
                          "Log transformed Growth Rate (λ)", 
                          "Log Generation time Vs Growth Rate in the Aves Clade"
                          , TRUE)
GenVGrowth2
```

## seperating duplicates?

```{r}
ComSingle <- ComSubFlag[which(
  duplicated(ComSubFlag$SpeciesAccepted)==FALSE),]
```

# IUCN RedList

## Acessing data

-   due to issues with data having to load from computer

```{r}
IUCN_data<- read.csv(here("IUCN_comadre_compadre.csv"))

comadre_iucn <- comadre_sub %>%
  left_join(x = ., y = IUCN_data, by = "SpeciesAccepted") %>% 
  mutate(IUCNstatus = case_when(
    IUCNstatus == "EN" ~ "Endangered",
    IUCNstatus == "VU" ~ "Vulnerable",
    IUCNstatus == "NT" ~ "Near Threatened",
    IUCNstatus == "LC" ~ "Least Concern",
    is.na(IUCNstatus) == TRUE ~ "Not Assessed"),
    IUCNstatus = factor(IUCNstatus, 
                        levels = c("Endangered","Vulnerable",
                                   "Near Threatened","Least Concern",
                                   "Not Assessed")))

comadre_iucn <- as.data.frame(comadre_iucn)

comadre_iucn$iucn_colour <- NA
comadre_iucn$iucn_colour[which(comadre_iucn$IUCNstatus == "Endangered")] <- "Orange" 
comadre_iucn$iucn_colour[which(comadre_iucn$IUCNstatus == "Vulnerable")] <- "Yellow"
comadre_iucn$iucn_colour[which(comadre_iucn$IUCNstatus == "Near Threatened")] <- "Dark green"
comadre_iucn$iucn_colour[which(comadre_iucn$IUCNstatus == "Least Concern")] <- "Green"
comadre_iucn$iucn_colour[which(comadre_iucn$IUCNstatus == "Not Assessed")] <- "Blue"
```

# open tree of life
